#server:
#  port: 8000

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#spring:
#  application:
#   name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: JIT-platform
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/JIT-platform/**
# application.yml
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service # 애플리케이션 이름, 임의로 작성해도 무관
  cloud:
    gateway:
      default-filters: # 모든 라우팅에 적용하는 필터
        - name: GlobalFilter # 적용할 필터의 클래스명
          args: # 필터 클래스의 Config 클래스 필드값 정보 세팅
            baseMessage: Spring Cloud Gateway Logger
            preLogger: true
            postLogger: true
      routes:
        - id: jit-factory
          predicates:
            - Path=/jit-factory/**
          uri: lb://JIT-FACTORY
          filters:
            - RewritePath=/jit-factory/(?<segment>.*), /$\{segment}


