server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jit?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: jit
    password: usg
  jpa:
    hibernate:
      ddl-auto: update # 처음에는 create


  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  defer-datasource-initialization: true
  #  hibernate:
  #    ddl-auto: create-drop
  #  properties:
  #    hibernate:
  #      format_sql: true
  #      show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  packages-to-scan: com.jit.backend
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: jit-factory-api.html    # Swagger UI ?? => localhost:8000/jit-factory-api.html
    tags-sorter: alpha            # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha      # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: dXNn6rO17Jyg64yA7ZWZ6rO87ZWo6ruY7ZWY64qU7Lqh7Iqk7Yak6rK97KeE64yA7ZqM7Iqk66eI7Yq47Yyp7Yag66as7J6F64uI64uk
  refresh-token-validity-in-seconds: 1209600 # 14일
  access-token-validity-in-seconds: 43200 # 12시간