spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jit?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: jit
    password: usg
  jpa:
    hibernate:
      ddl-auto: update # 처음에는 create


  #jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
  #  defer-datasource-initialization: true
  #  hibernate:
  #    ddl-auto: create-drop
  #  properties:
  #    hibernate:
  #      format_sql: true
  #      show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging.level:
  org.hibernate.SQL: debug