spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: sbs-dev
    password: factory1621
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true